### ISSUE TITLE
comand line?

### ISSUE THREAD

**Issue by gogolo2** [lihas/windows-DPI-scaling-sample#1]
Hi 
This is a great tool. Is it possible to start DPIScalingMFCApp.exe from command line without gui and set a dpi? Thx!

**Comment by lihas** [comment]
It certainly can be done. Let me think about it. Would a command line tool be good, or should I expose the API via COM/ATL? both will offer similar functionality.

**Comment by gogolo2** [comment]
Thx for your reply! A command line tool would be perfect.

**Comment by imniko** [comment]
I made a command line only project, though it only has one function, set a custom scaling to a specified monitor. I consider myself a beginner in C++, so a more refined version from the author himself would be nice to have. here is my project link https://github.com/imniko/SetDPI as it is my first project published to github, its not very pretty but it works.

**Comment by gogolo2** [comment]
Thx very much, this ist great! The possibility to operate it with AHK is exactely what I wanted to do and gives us so much possibilites. I hope other will find it useful too! Thx again.

**Comment by lihas** [comment]
Thanks @imniko .
I have included a link to your repo on my project's readme page. for those looking for a command line version.
