### ISSUE TITLE
Command line for DPIScalingMFCApp

### ISSUE THREAD

**Issue by cgarst** [lihas/windows-DPI-scaling-sample#3]
Command line support with DPIScalingMFCApp would be wonderful for scripting purposes.

**Comment by lihas** [comment]
A user created a command line version of this tool. See this thread - https://github.com/lihas/windows-DPI-scaling-sample/issues/1
Direct link - https://github.com/imniko/SetDPI
I have not tested it, but seeing the description it seems great.
I will not be making another tool.
However I am working on a DLL version of the lib.
Powershell script, auto hotkey etc support calling DLL functions.
So it will help those wanting to script using the DLL.

**Comment by cgarst** [comment]
Excellent, thanks!
